### ISSUE TITLE
Contributors List

### ISSUE THREAD

**Issue by StaneCobalt** [AcmSemo/AlgoLib#11]
Add a list for contributors to the readme

**Comment by IAmBullsaw** [comment]
Hi, 👋 

Should this list be styled in any specific way, contain specific information or even (if possible) be automagical?

BR

**Comment by Jpfonseca** [comment]
@StaneCobalt  is this done already ?? If so can you close the issue ? if not can I pick it ?

**Comment by StaneCobalt** [comment]
If you want to create a separate contributors.md and transfer / update our current contributors list, go for it!

**Comment by Jpfonseca** [comment]
Ok on It
