### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by StaneCobalt** [AcmSemo/AlgoLib#5]
Add a quick sort algorithm

**Comment by dhairyakhale** [comment]
I would like to take up this issue.

**Comment by StaneCobalt** [comment]
Go for it my man, I'll leave the issue open though, cause we're accepting multiple solutions. Just do it in whatever language(s) you want!

**Comment by dhairyakhale** [comment]
@StaneCobalt Can you delete the a.out file? I mistakenly left that file in, while I was supposed to delete it. Sorry.

**Comment by MarshalX** [comment]
https://github.com/AcmSemo/AlgoLib/pull/52

**Comment by csp98** [comment]
Java (PR #61)
